---
name: Build firmware - BLUETOOTH
on:
  push:
    branches:
      - "master"
    tags:
      - v*
    paths:
      - "build-firmwares-bluetooth.sh"
      - ".github/workflows/fw-build-bluetooth.yml"
  workflow_dispatch:

concurrency:
  group: "fw-build-bluetooth"
  cancel-in-progress: true

jobs:
  build:
    name: Build firmware
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target:
          - t16
          - t18
          - zorro
          - tx12;tx12mk2;boxer
          - tx16s
          - x10;x10-access
          - x12s
          - x7;x7-access
          - x9lites
          - xlite
    container:
      image: ghcr.io/edgetx/edgetx-dev:2.10.0
      volumes:
        - ${{ github.workspace }}:/src
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Build firmware with BLUETOOTH ${{ matrix.target }}
        env:
          FLAVOR: ${{ matrix.target }}
          EDGETX_VERSION_SUFFIX: lang-custom
        run: ./build-firmwares-bluetooth.sh

      - name: Package firmware ${{ matrix.target }}
        uses: actions/upload-artifact@v4
        with:
          name: edgetx-firmware-custom-${{ matrix.target }}
          path: |
            *.zip
          retention-days: 15
          if-no-files-found: error

  deploy:
    name: Deploy release
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          pattern: edgetx-firmware-custom-*
          path: edgetx-firmware-custom
          merge-multiple: true

      - name: Deploy release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.event.ref, 'refs/tags/v')
        with:
          token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          generate_release_notes: true
          files: |
            edgetx-firmware-custom/*.zip

      - name: Deploy pre-release
        uses: softprops/action-gh-release@v1
        if: ${{ !startsWith(github.event.ref, 'refs/tags/v') }}
        with:
          token: "${{ secrets.GITHUB_TOKEN }}"
          tag_name: "latest"
          prerelease: true
          generate_release_notes: true
          files: |
            edgetx-firmware-custom/*.zip
